spring:
  datasource:
    url: jdbc:mysql://206.81.20.220:3306/railway?userUnicode=yes&characterEncoding=utf8&reconnect=true
    username: igor
    password: igor
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 30000
      minimum-idle: 0
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate