spring:
  datasource:
    url: jdbc:mysql://206.81.20.220:3306/iv-player?userUnicode=yes&characterEncoding=utf8&reconnect=true
    username: igor
    password: igor
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 30000
      minimum-idle: 0
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate

server:
  ssl:
    key-store-type: PKCS12 # Тип хранилища ключей (альтернатива JKS)
    key-store: classpath:keystore/iv-player.p12 # Путь до хранилища ключей
    key-store-password: i1g9o9r7
    key-alias: iv-player


# Не выводить в логах CONDITIONS EVALUATION REPORT при старте (только в случае ошибки)
logging:
  level:
    org.springframework.boot.autoconfigure: ERROR


debug: true